version: '3.8'

services:
  telegram-bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./downloads:/app/downloads
      - ./sessions:/app/sessions
      - ./stats.json:/app/stats.json
    restart: unless-stopped
    
  # إضافة Redis للتخزين المؤقت (اختياري)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
